<?php

/*
 * Implementation of hook_menu().
 */
function black_list_domains_menu() {

  $items = array();

  $items['admin/black-list-domains'] = array(
    'title' => 'Black List Domains Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('black_list_domains_admin'),
    'access arguments' => array('administer black list domains settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}


function black_list_domains_admin() {
  $form = array();

  $form['black_list_domains_data'] = array(
    '#type' => 'textarea',
    '#title' => t('Domain Black list'),
    '#default_value' => variable_get('black_list_domains_data', ''),
    '#description' => t("Domain by line"),
    '#required' => TRUE
  );

  return system_settings_form($form);
}

/*
 * Implementation of hook_page_alter().
 */
function black_list_domains_page_alter(&$page) {
	
	// tal y como está la configuración de este Drupal, solo tenemos que revisar el contenido del nodo 
	// y de los posibles bloques de la region sidebar_first
	// en el caso de existir menús, views, campos en el nodo u otras regiones debería ampliarse este código

	$domains = preg_split('/\r\n|[\r\n]/', variable_get('black_list_domains_data', ''));

	foreach($domains as $domain) {

		$pattern = '|<a [^>]*href="'.$domain.'[^"]*"[^>]*>.*</a>|iU';

		//region  Content - Body node
		if(isset($page['content']['system_main']['nodes'])){
			$page['content']['system_main']['nodes'][1]['body'][0]['#markup'] = preg_replace($pattern, '', $page['content']['system_main']['nodes'][1]['body'][0]['#markup']);
		}

		//region sidebar first - content blocks
		if(isset($page['sidebar_first'])){
			foreach( $page['sidebar_first'] as $key => $block) {
				if( isset($block['#markup']) ){
					$page['sidebar_first'][$key]['#markup'] = preg_replace($pattern, '', $page['sidebar_first'][$key]['#markup']);
				}
			}
		}

	}
	
}

?>